export type TemplateCategory =
  | "Technology"
  | "Data"
  | "Business"
  | "Corporate"
  | "Entry-Level"
  | "Creative"
  | "Executive"
  | "Modern"
  | "Minimal"
  | "Photo"
  | "Experienced";

export type TemplateLayout =
  | "classic"
  | "sidebar-left"
  | "sidebar-right"
  | "header-band"
  | "two-column"
  | "timeline";

export type ExperienceLevel = "Entry level" | "Mid level" | "Senior" | "Executive" | "All levels";

export interface ResumeTemplate {
  id: string;
  name: string;
  role: string;
  category: TemplateCategory;
  layout: TemplateLayout;
  accent: string;
  headingFont: "sans" | "serif";
  uppercaseHeadings: boolean;
  rule: "line" | "band" | "none";
  atsScore: number;
  readability: number;
  popular?: boolean;
  isNew?: boolean;
  premium?: boolean;
  modern?: boolean;
  recruiterFavorite?: boolean;
  withPhoto?: boolean;
  experienceLevel: ExperienceLevel;
  roles: string[];
  /** which dummy-content role profile powers this template */
  contentRole?: string;
  blurb: string;
}

export const TEMPLATES: ResumeTemplate[] = [
  {
    id: "software-engineer",
    name: "Software Engineer",
    role: "Software Engineer",
    category: "Technology",
    layout: "classic",
    accent: "#1d4ed8",
    headingFont: "sans",
    uppercaseHeadings: true,
    rule: "line",
    atsScore: 98,
    readability: 96,
    popular: true,
    recruiterFavorite: true,
    experienceLevel: "Mid level",
    roles: ["Software Engineer", "Backend Engineer", "SDE II"],
    blurb: "Single-column engineering resume with impact-led bullets and a deep tech stack.",
  },
  {
    id: "python-developer",
    name: "Python Developer",
    role: "Python Developer",
    category: "Technology",
    layout: "sidebar-left",
    accent: "#0f766e",
    headingFont: "sans",
    uppercaseHeadings: true,
    rule: "line",
    atsScore: 95,
    readability: 95,
    popular: true,
    experienceLevel: "Mid level",
    roles: ["Python Developer", "Django Engineer", "Backend Developer"],
    blurb: "Skills-forward sidebar tuned for Django, FastAPI and data-heavy backend roles.",
  },
  {
    id: "full-stack-developer",
    name: "Full Stack Developer",
    role: "Full Stack Developer",
    category: "Technology",
    layout: "timeline",
    accent: "#2563eb",
    headingFont: "sans",
    uppercaseHeadings: false,
    rule: "line",
    atsScore: 94,
    readability: 96,
    popular: true,
    experienceLevel: "Mid level",
    roles: ["Full Stack Developer", "MERN Developer", "Product Engineer"],
    blurb: "Career-progression timeline that shows front-end and back-end ownership at a glance.",
  },
  {
    id: "data-analyst",
    name: "Data Analyst",
    role: "Data Analyst",
    category: "Data",
    layout: "sidebar-right",
    accent: "#0369a1",
    headingFont: "sans",
    uppercaseHeadings: true,
    rule: "line",
    atsScore: 96,
    readability: 94,
    experienceLevel: "Mid level",
    roles: ["Data Analyst", "BI Analyst", "Product Analyst"],
    blurb: "Metric-first layout with a tools rail for SQL, Python, Power BI and Tableau.",
  },
  {
    id: "sales-executive",
    name: "Sales Executive",
    role: "Sales Executive",
    category: "Business",
    layout: "header-band",
    accent: "#1e40af",
    headingFont: "sans",
    uppercaseHeadings: true,
    rule: "band",
    atsScore: 93,
    readability: 95,
    popular: true,
    experienceLevel: "Senior",
    roles: ["Sales Executive", "Account Manager", "BD Manager"],
    blurb: "Quota, revenue and territory numbers front and centre under a confident header band.",
  },
  {
    id: "hr-professional",
    name: "HR Professional",
    role: "HR Professional",
    category: "Business",
    layout: "classic",
    accent: "#3730a3",
    headingFont: "sans",
    uppercaseHeadings: true,
    rule: "line",
    atsScore: 96,
    readability: 95,
    experienceLevel: "Mid level",
    roles: ["HR Generalist", "HRBP", "Talent Acquisition"],
    blurb: "People-operations format covering hiring, engagement, compliance and HR analytics.",
  },
  {
    id: "marketing-executive",
    name: "Marketing Executive",
    role: "Marketing Executive",
    category: "Business",
    layout: "two-column",
    accent: "#0284c7",
    headingFont: "sans",
    uppercaseHeadings: false,
    rule: "line",
    atsScore: 92,
    readability: 94,
    isNew: true,
    experienceLevel: "Mid level",
    roles: ["Marketing Executive", "Growth Manager", "Brand Manager"],
    blurb: "Campaign-led structure balancing creative work with ROAS, CAC and growth metrics.",
  },
  {
    id: "finance-professional",
    name: "Finance Professional",
    role: "Finance Professional",
    category: "Corporate",
    layout: "classic",
    accent: "#1e3a5f",
    headingFont: "serif",
    uppercaseHeadings: true,
    rule: "line",
    atsScore: 97,
    readability: 94,
    recruiterFavorite: true,
    experienceLevel: "Senior",
    roles: ["Financial Analyst", "FP&A", "Chartered Accountant"],
    blurb: "Conservative CA / FP&A formatting built for audit, controllership and banking panels.",
  },
  {
    id: "customer-success",
    name: "Customer Success Manager",
    role: "Customer Success Manager",
    category: "Corporate",
    layout: "sidebar-left",
    accent: "#0e7490",
    headingFont: "sans",
    uppercaseHeadings: true,
    rule: "line",
    atsScore: 94,
    readability: 96,
    experienceLevel: "Mid level",
    roles: ["Customer Success Manager", "Account Manager", "Support Lead"],
    blurb: "Retention, CSAT and escalation outcomes with a support-tooling capability rail.",
  },
  {
    id: "fresher-graduate",
    name: "Fresher / Graduate",
    role: "Computer Science Graduate",
    category: "Entry-Level",
    layout: "classic",
    accent: "#2563eb",
    headingFont: "sans",
    uppercaseHeadings: true,
    rule: "line",
    atsScore: 95,
    readability: 97,
    isNew: true,
    experienceLevel: "Entry level",
    roles: ["Fresher", "Graduate Trainee", "Intern"],
    blurb: "Education, internships and projects ordered exactly how campus recruiters scan them.",
  },

  /* ---------- Premium / creative collection ---------- */
  {
    id: "designer-portfolio",
    name: "Designer Portfolio",
    role: "Product Designer",
    category: "Creative",
    layout: "sidebar-left",
    accent: "#7c3aed",
    headingFont: "sans",
    uppercaseHeadings: false,
    rule: "line",
    atsScore: 91,
    readability: 97,
    isNew: true,
    premium: true,
    modern: true,
    withPhoto: true,
    experienceLevel: "Mid level",
    roles: ["Product Designer", "UI/UX Designer", "Visual Designer"],
    contentRole: "marketing-executive",
    blurb: "Photo-led creative layout with a portfolio rail — expressive yet still ATS-parsable.",
  },
  {
    id: "executive-suite",
    name: "Executive Resume",
    role: "Vice President, Operations",
    category: "Executive",
    layout: "header-band",
    accent: "#0f172a",
    headingFont: "serif",
    uppercaseHeadings: true,
    rule: "band",
    atsScore: 96,
    readability: 94,
    isNew: true,
    premium: true,
    recruiterFavorite: true,
    experienceLevel: "Executive",
    roles: ["VP", "Director", "Head of Department"],
    contentRole: "finance-professional",
    blurb: "Dark executive band, luxury serif typography and boardroom-ready leadership framing.",
  },
  {
    id: "fresher-spark",
    name: "Fresher Resume",
    role: "Graduate Applicant",
    category: "Entry-Level",
    layout: "two-column",
    accent: "#0ea5e9",
    headingFont: "sans",
    uppercaseHeadings: false,
    rule: "line",
    atsScore: 95,
    readability: 98,
    isNew: true,
    modern: true,
    experienceLevel: "Entry level",
    roles: ["Fresher", "Intern", "Trainee"],
    contentRole: "fresher-graduate",
    blurb: "Simple, attractive entry-level format leading with internships, projects and achievements.",
  },
  {
    id: "startup-bold",
    name: "Startup Resume",
    role: "Founding Engineer",
    category: "Modern",
    layout: "two-column",
    accent: "#ea580c",
    headingFont: "sans",
    uppercaseHeadings: true,
    rule: "line",
    atsScore: 93,
    readability: 96,
    isNew: true,
    modern: true,
    experienceLevel: "Mid level",
    roles: ["Founding Engineer", "Generalist", "Product Manager"],
    contentRole: "full-stack-developer",
    blurb: "Bold headings and generous spacing built for high-ownership startup applications.",
  },
  {
    id: "creative-timeline",
    name: "Creative Resume",
    role: "Content & Brand Lead",
    category: "Creative",
    layout: "timeline",
    accent: "#db2777",
    headingFont: "sans",
    uppercaseHeadings: false,
    rule: "line",
    atsScore: 92,
    readability: 96,
    isNew: true,
    modern: true,
    experienceLevel: "Mid level",
    roles: ["Content Lead", "Brand Manager", "Creative Strategist"],
    contentRole: "marketing-executive",
    blurb: "Accent-coloured career timeline that reads like a story without breaking parsers.",
  },
  {
    id: "luxury-gold",
    name: "Luxury Resume",
    role: "Managing Director",
    category: "Executive",
    layout: "header-band",
    accent: "#b8860b",
    headingFont: "serif",
    uppercaseHeadings: true,
    rule: "band",
    atsScore: 94,
    readability: 93,
    isNew: true,
    premium: true,
    experienceLevel: "Executive",
    roles: ["Managing Director", "Partner", "Chief of Staff"],
    contentRole: "sales-executive",
    blurb: "Black-and-gold executive styling for senior corporate and consulting mandates.",
  },
  {
    id: "blue-corporate",
    name: "Blue Corporate Resume",
    role: "Business Analyst",
    category: "Corporate",
    layout: "classic",
    accent: "#1d4ed8",
    headingFont: "sans",
    uppercaseHeadings: true,
    rule: "line",
    atsScore: 98,
    readability: 96,
    isNew: true,
    recruiterFavorite: true,
    experienceLevel: "All levels",
    roles: ["Business Analyst", "Operations", "Consultant"],
    contentRole: "hr-professional",
    blurb: "The safest possible corporate format — minimal, blue-accented, maximum ATS score.",
  },
  {
    id: "creative-sidebar",
    name: "Creative Sidebar Resume",
    role: "Digital Marketer",
    category: "Creative",
    layout: "sidebar-right",
    accent: "#0891b2",
    headingFont: "sans",
    uppercaseHeadings: false,
    rule: "line",
    atsScore: 90,
    readability: 97,
    isNew: true,
    premium: true,
    withPhoto: true,
    experienceLevel: "Mid level",
    roles: ["Digital Marketer", "Designer", "Community Lead"],
    contentRole: "customer-success",
    blurb: "Coloured sidebar with photo and skill emphasis — personality with clean parsing.",
  },
  {
    id: "elegant-minimal",
    name: "Elegant Resume",
    role: "Strategy Consultant",
    category: "Minimal",
    layout: "classic",
    accent: "#334155",
    headingFont: "serif",
    uppercaseHeadings: false,
    rule: "none",
    atsScore: 97,
    readability: 98,
    isNew: true,
    premium: true,
    experienceLevel: "All levels",
    roles: ["Consultant", "Researcher", "Writer"],
    contentRole: "finance-professional",
    blurb: "Large whitespace and beautiful serif typography for a quietly confident impression.",
  },
  {
    id: "genz-minimal",
    name: "Gen Z Minimal",
    role: "Junior Developer",
    category: "Modern",
    layout: "classic",
    accent: "#16a34a",
    headingFont: "sans",
    uppercaseHeadings: false,
    rule: "line",
    atsScore: 96,
    readability: 98,
    isNew: true,
    modern: true,
    experienceLevel: "Entry level",
    roles: ["Junior Developer", "Associate", "Intern"],
    contentRole: "python-developer",
    blurb: "Clean, modern and unfussy — bold type, tight sections, zero visual noise.",
  },

  /* ---------- Phase 3: Gen Z / Millennial collection ---------- */
  {
    id: "modern-photo",
    name: "Modern Photo Resume",
    role: "UI/UX Designer",
    category: "Photo",
    layout: "sidebar-left",
    accent: "#4f46e5",
    headingFont: "sans",
    uppercaseHeadings: false,
    rule: "line",
    atsScore: 93,
    readability: 97,
    isNew: true,
    modern: true,
    withPhoto: true,
    experienceLevel: "Mid level",
    roles: ["UI/UX Designer", "Product Designer", "Front-end Developer"],
    contentRole: "marketing-executive",
    blurb: "Large circular profile photo, clean type and an airy modern grid.",
  },
  {
    id: "executive-photo",
    name: "Executive Photo Resume",
    role: "Operations Director",
    category: "Photo",
    layout: "sidebar-right",
    accent: "#1e293b",
    headingFont: "serif",
    uppercaseHeadings: true,
    rule: "line",
    atsScore: 95,
    readability: 94,
    isNew: true,
    premium: true,
    withPhoto: true,
    experienceLevel: "Executive",
    roles: ["Director", "General Manager", "Head of Operations"],
    contentRole: "finance-professional",
    blurb: "Square corporate photo with restrained serif headings for leadership roles.",
  },
  {
    id: "creative-portfolio",
    name: "Creative Portfolio Resume",
    role: "Brand Designer",
    category: "Creative",
    layout: "two-column",
    accent: "#c026d3",
    headingFont: "sans",
    uppercaseHeadings: false,
    rule: "line",
    atsScore: 91,
    readability: 96,
    isNew: true,
    premium: true,
    modern: true,
    withPhoto: true,
    experienceLevel: "Mid level",
    roles: ["Brand Designer", "Art Director", "Content Designer"],
    contentRole: "marketing-executive",
    blurb: "Portfolio-forward layout with vivid accents for design and content folios.",
  },
  {
    id: "startup-cards",
    name: "Startup Card Resume",
    role: "Product Manager",
    category: "Modern",
    layout: "two-column",
    accent: "#f97316",
    headingFont: "sans",
    uppercaseHeadings: true,
    rule: "line",
    atsScore: 94,
    readability: 96,
    isNew: true,
    modern: true,
    experienceLevel: "Mid level",
    roles: ["Product Manager", "Growth Lead", "Founding Engineer"],
    contentRole: "full-stack-developer",
    blurb: "Bold headings and card-like sections for fast-moving startup applications.",
  },
  {
    id: "minimal-white",
    name: "Minimal White Resume",
    role: "Business Analyst",
    category: "Minimal",
    layout: "classic",
    accent: "#0f172a",
    headingFont: "sans",
    uppercaseHeadings: false,
    rule: "none",
    atsScore: 98,
    readability: 98,
    isNew: true,
    experienceLevel: "All levels",
    roles: ["Business Analyst", "Operations", "Program Manager"],
    contentRole: "hr-professional",
    blurb: "Generous whitespace, elegant type and the cleanest possible parsing.",
  },
  {
    id: "dark-premium",
    name: "Dark Premium Resume",
    role: "Engineering Manager",
    category: "Executive",
    layout: "header-band",
    accent: "#111827",
    headingFont: "serif",
    uppercaseHeadings: true,
    rule: "band",
    atsScore: 93,
    readability: 93,
    isNew: true,
    premium: true,
    experienceLevel: "Senior",
    roles: ["Engineering Manager", "Principal Engineer", "Head of Tech"],
    contentRole: "software-engineer",
    blurb: "Charcoal band with gold-tinted accents for a high-end executive impression.",
  },
  {
    id: "career-timeline",
    name: "Timeline Resume",
    role: "Full Stack Developer",
    category: "Modern",
    layout: "timeline",
    accent: "#0891b2",
    headingFont: "sans",
    uppercaseHeadings: false,
    rule: "line",
    atsScore: 94,
    readability: 97,
    isNew: true,
    modern: true,
    experienceLevel: "Mid level",
    roles: ["Full Stack Developer", "Software Engineer", "Tech Lead"],
    contentRole: "full-stack-developer",
    blurb: "A visual career timeline that shows growth and tenure at a glance.",
  },
  {
    id: "sidebar-pro",
    name: "Sidebar Resume",
    role: "Customer Support Lead",
    category: "Photo",
    layout: "sidebar-left",
    accent: "#0d9488",
    headingFont: "sans",
    uppercaseHeadings: true,
    rule: "line",
    atsScore: 94,
    readability: 96,
    isNew: true,
    withPhoto: true,
    experienceLevel: "Mid level",
    roles: ["Customer Support", "Success Manager", "Operations Executive"],
    contentRole: "customer-success",
    blurb: "Coloured left rail with photo, contact block and a compact skills panel.",
  },
  {
    id: "fresher-launch",
    name: "Fresher Launch Resume",
    role: "Graduate Engineer",
    category: "Entry-Level",
    layout: "classic",
    accent: "#2563eb",
    headingFont: "sans",
    uppercaseHeadings: true,
    rule: "line",
    atsScore: 96,
    readability: 98,
    isNew: true,
    modern: true,
    experienceLevel: "Entry level",
    roles: ["Fresher", "Intern", "Graduate Trainee"],
    contentRole: "fresher-graduate",
    blurb: "Skills-first fresher format leading with internships, projects and certifications.",
  },
  {
    id: "gradient-modern",
    name: "Modern Gradient Resume",
    role: "Data Analyst",
    category: "Modern",
    layout: "header-band",
    accent: "#6366f1",
    headingFont: "sans",
    uppercaseHeadings: false,
    rule: "band",
    atsScore: 92,
    readability: 97,
    isNew: true,
    premium: true,
    modern: true,
    experienceLevel: "Mid level",
    roles: ["Data Analyst", "Product Analyst", "Marketing Analyst"],
    contentRole: "data-analyst",
    blurb: "Soft blue-violet header with rounded section cards and a premium finish.",
  },
];

export const CATEGORIES: ("All" | TemplateCategory)[] = [
  "All",
  "Technology",
  "Data",
  "Business",
  "Corporate",
  "Creative",
  "Executive",
  "Modern",
  "Minimal",
  "Photo",
  "Entry-Level",
  "Experienced",
];

export const getTemplate = (id: string): ResumeTemplate =>
  TEMPLATES.find((t) => t.id === id) ?? TEMPLATES[0];


export const templateContentRole = (t: ResumeTemplate) => t.contentRole ?? t.id;

/** Friendly, human document title for a template-backed resume. */
export const templateDocTitle = (id: string) => {
  const t = TEMPLATES.find((x) => x.id === id);
  if (!t) return "My Resume";
  return /resume$/i.test(t.name) ? t.name : `${t.name} Resume`;
};
