/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as CoursesCourseIdIndexRouteImport } from './routes/courses.$courseId.index'
import { Route as CoursesCourseIdUnitIdRouteImport } from './routes/courses.$courseId.$unitId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdIndexRoute = CoursesCourseIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesCourseIdRoute,
} as any)
const CoursesCourseIdUnitIdRoute = CoursesCourseIdUnitIdRouteImport.update({
  id: '/$unitId',
  path: '/$unitId',
  getParentRoute: () => CoursesCourseIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/downloads': typeof DownloadsRoute
  '/courses/$courseId': typeof CoursesCourseIdRouteWithChildren
  '/courses/$courseId/$unitId': typeof CoursesCourseIdUnitIdRoute
  '/courses/$courseId/': typeof CoursesCourseIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/downloads': typeof DownloadsRoute
  '/courses/$courseId/$unitId': typeof CoursesCourseIdUnitIdRoute
  '/courses/$courseId': typeof CoursesCourseIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/downloads': typeof DownloadsRoute
  '/courses/$courseId': typeof CoursesCourseIdRouteWithChildren
  '/courses/$courseId/$unitId': typeof CoursesCourseIdUnitIdRoute
  '/courses/$courseId/': typeof CoursesCourseIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/downloads'
    | '/courses/$courseId'
    | '/courses/$courseId/$unitId'
    | '/courses/$courseId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/downloads'
    | '/courses/$courseId/$unitId'
    | '/courses/$courseId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/downloads'
    | '/courses/$courseId'
    | '/courses/$courseId/$unitId'
    | '/courses/$courseId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DownloadsRoute: typeof DownloadsRoute
  CoursesCourseIdRoute: typeof CoursesCourseIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId/': {
      id: '/courses/$courseId/'
      path: '/'
      fullPath: '/courses/$courseId/'
      preLoaderRoute: typeof CoursesCourseIdIndexRouteImport
      parentRoute: typeof CoursesCourseIdRoute
    }
    '/courses/$courseId/$unitId': {
      id: '/courses/$courseId/$unitId'
      path: '/$unitId'
      fullPath: '/courses/$courseId/$unitId'
      preLoaderRoute: typeof CoursesCourseIdUnitIdRouteImport
      parentRoute: typeof CoursesCourseIdRoute
    }
  }
}

interface CoursesCourseIdRouteChildren {
  CoursesCourseIdUnitIdRoute: typeof CoursesCourseIdUnitIdRoute
  CoursesCourseIdIndexRoute: typeof CoursesCourseIdIndexRoute
}

const CoursesCourseIdRouteChildren: CoursesCourseIdRouteChildren = {
  CoursesCourseIdUnitIdRoute: CoursesCourseIdUnitIdRoute,
  CoursesCourseIdIndexRoute: CoursesCourseIdIndexRoute,
}

const CoursesCourseIdRouteWithChildren = CoursesCourseIdRoute._addFileChildren(
  CoursesCourseIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DownloadsRoute: DownloadsRoute,
  CoursesCourseIdRoute: CoursesCourseIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
