/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatYouGetRouteImport } from './routes/what-you-get'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as IndexRouteImport } from './routes/index'

const WhatYouGetRoute = WhatYouGetRouteImport.update({
  id: '/what-you-get',
  path: '/what-you-get',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/how-it-works': typeof HowItWorksRoute
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/what-you-get': typeof WhatYouGetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/how-it-works': typeof HowItWorksRoute
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/what-you-get': typeof WhatYouGetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/how-it-works': typeof HowItWorksRoute
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/what-you-get': typeof WhatYouGetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/builder'
    | '/how-it-works'
    | '/reviews'
    | '/sitemap.xml'
    | '/what-you-get'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/builder'
    | '/how-it-works'
    | '/reviews'
    | '/sitemap.xml'
    | '/what-you-get'
  id:
    | '__root__'
    | '/'
    | '/builder'
    | '/how-it-works'
    | '/reviews'
    | '/sitemap.xml'
    | '/what-you-get'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuilderRoute: typeof BuilderRoute
  HowItWorksRoute: typeof HowItWorksRoute
  ReviewsRoute: typeof ReviewsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WhatYouGetRoute: typeof WhatYouGetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/what-you-get': {
      id: '/what-you-get'
      path: '/what-you-get'
      fullPath: '/what-you-get'
      preLoaderRoute: typeof WhatYouGetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuilderRoute: BuilderRoute,
  HowItWorksRoute: HowItWorksRoute,
  ReviewsRoute: ReviewsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WhatYouGetRoute: WhatYouGetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
