/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AtsScoreCheckerRouteImport } from './routes/ats-score-checker'
import { Route as BechnaseekhoRouteImport } from './routes/bechnaseekho'
import { Route as CareersyncRouteImport } from './routes/careersync'
import { Route as CareersyncAcademyRouteImport } from './routes/careersync-academy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as FindJobsRouteImport } from './routes/find-jobs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PostJobRouteImport } from './routes/post-job'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ResumeTemplatesRouteImport } from './routes/resume-templates'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as CareersyncAcademyIndexRouteImport } from './routes/careersync-academy.index'
import { Route as CareersyncAboutRouteImport } from './routes/careersync.about'
import { Route as CareersyncBlogsRouteImport } from './routes/careersync.blogs'
import { Route as CareersyncJobsRouteImport } from './routes/careersync.jobs'
import { Route as CareersyncJourneyRouteImport } from './routes/careersync.journey'
import { Route as CareersyncNotificationsRouteImport } from './routes/careersync.notifications'
import { Route as CareersyncVerifiedRecruitersRouteImport } from './routes/careersync.verified-recruiters'
import { Route as ApiPublicReportErrorRouteImport } from './routes/api/public/report-error'
import { Route as CareersyncAcademyCoursesCourseIdRouteImport } from './routes/careersync-academy.courses.$courseId'
import { Route as CareersyncBlogsSlugRouteImport } from './routes/careersync.blogs.$slug'
import { Route as CareersyncAcademyCoursesCourseIdIndexRouteImport } from './routes/careersync-academy.courses.$courseId.index'
import { Route as CareersyncAcademyCoursesCourseIdUnitIdRouteImport } from './routes/careersync-academy.courses.$courseId.$unitId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AtsScoreCheckerRoute = AtsScoreCheckerRouteImport.update({
  id: '/ats-score-checker',
  path: '/ats-score-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const BechnaseekhoRoute = BechnaseekhoRouteImport.update({
  id: '/bechnaseekho',
  path: '/bechnaseekho',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersyncRoute = CareersyncRouteImport.update({
  id: '/careersync',
  path: '/careersync',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersyncAcademyRoute = CareersyncAcademyRouteImport.update({
  id: '/careersync-academy',
  path: '/careersync-academy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const FindJobsRoute = FindJobsRouteImport.update({
  id: '/find-jobs',
  path: '/find-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PostJobRoute = PostJobRouteImport.update({
  id: '/post-job',
  path: '/post-job',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeTemplatesRoute = ResumeTemplatesRouteImport.update({
  id: '/resume-templates',
  path: '/resume-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersyncAcademyIndexRoute = CareersyncAcademyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CareersyncAcademyRoute,
} as any)
const CareersyncAboutRoute = CareersyncAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => CareersyncRoute,
} as any)
const CareersyncBlogsRoute = CareersyncBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => CareersyncRoute,
} as any)
const CareersyncJobsRoute = CareersyncJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => CareersyncRoute,
} as any)
const CareersyncJourneyRoute = CareersyncJourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => CareersyncRoute,
} as any)
const CareersyncNotificationsRoute = CareersyncNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => CareersyncRoute,
} as any)
const CareersyncVerifiedRecruitersRoute =
  CareersyncVerifiedRecruitersRouteImport.update({
    id: '/verified-recruiters',
    path: '/verified-recruiters',
    getParentRoute: () => CareersyncRoute,
  } as any)
const ApiPublicReportErrorRoute = ApiPublicReportErrorRouteImport.update({
  id: '/api/public/report-error',
  path: '/api/public/report-error',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersyncAcademyCoursesCourseIdRoute =
  CareersyncAcademyCoursesCourseIdRouteImport.update({
    id: '/courses/$courseId',
    path: '/courses/$courseId',
    getParentRoute: () => CareersyncAcademyRoute,
  } as any)
const CareersyncBlogsSlugRoute = CareersyncBlogsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CareersyncBlogsRoute,
} as any)
const CareersyncAcademyCoursesCourseIdIndexRoute =
  CareersyncAcademyCoursesCourseIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CareersyncAcademyCoursesCourseIdRoute,
  } as any)
const CareersyncAcademyCoursesCourseIdUnitIdRoute =
  CareersyncAcademyCoursesCourseIdUnitIdRouteImport.update({
    id: '/$unitId',
    path: '/$unitId',
    getParentRoute: () => CareersyncAcademyCoursesCourseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ats-score-checker': typeof AtsScoreCheckerRoute
  '/bechnaseekho': typeof BechnaseekhoRoute
  '/careersync': typeof CareersyncRouteWithChildren
  '/careersync-academy': typeof CareersyncAcademyRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/find-jobs': typeof FindJobsRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/post-job': typeof PostJobRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/resume-templates': typeof ResumeTemplatesRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/careersync/about': typeof CareersyncAboutRoute
  '/careersync/blogs': typeof CareersyncBlogsRouteWithChildren
  '/careersync/jobs': typeof CareersyncJobsRoute
  '/careersync/journey': typeof CareersyncJourneyRoute
  '/careersync/notifications': typeof CareersyncNotificationsRoute
  '/careersync/verified-recruiters': typeof CareersyncVerifiedRecruitersRoute
  '/careersync-academy/': typeof CareersyncAcademyIndexRoute
  '/api/public/report-error': typeof ApiPublicReportErrorRoute
  '/careersync-academy/courses/$courseId': typeof CareersyncAcademyCoursesCourseIdRouteWithChildren
  '/careersync/blogs/$slug': typeof CareersyncBlogsSlugRoute
  '/careersync-academy/courses/$courseId/$unitId': typeof CareersyncAcademyCoursesCourseIdUnitIdRoute
  '/careersync-academy/courses/$courseId/': typeof CareersyncAcademyCoursesCourseIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ats-score-checker': typeof AtsScoreCheckerRoute
  '/bechnaseekho': typeof BechnaseekhoRoute
  '/careersync': typeof CareersyncRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/find-jobs': typeof FindJobsRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/post-job': typeof PostJobRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/resume-templates': typeof ResumeTemplatesRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/careersync/about': typeof CareersyncAboutRoute
  '/careersync/blogs': typeof CareersyncBlogsRouteWithChildren
  '/careersync/jobs': typeof CareersyncJobsRoute
  '/careersync/journey': typeof CareersyncJourneyRoute
  '/careersync/notifications': typeof CareersyncNotificationsRoute
  '/careersync/verified-recruiters': typeof CareersyncVerifiedRecruitersRoute
  '/careersync-academy': typeof CareersyncAcademyIndexRoute
  '/api/public/report-error': typeof ApiPublicReportErrorRoute
  '/careersync/blogs/$slug': typeof CareersyncBlogsSlugRoute
  '/careersync-academy/courses/$courseId/$unitId': typeof CareersyncAcademyCoursesCourseIdUnitIdRoute
  '/careersync-academy/courses/$courseId': typeof CareersyncAcademyCoursesCourseIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ats-score-checker': typeof AtsScoreCheckerRoute
  '/bechnaseekho': typeof BechnaseekhoRoute
  '/careersync': typeof CareersyncRouteWithChildren
  '/careersync-academy': typeof CareersyncAcademyRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/find-jobs': typeof FindJobsRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/post-job': typeof PostJobRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/resume-templates': typeof ResumeTemplatesRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/careersync/about': typeof CareersyncAboutRoute
  '/careersync/blogs': typeof CareersyncBlogsRouteWithChildren
  '/careersync/jobs': typeof CareersyncJobsRoute
  '/careersync/journey': typeof CareersyncJourneyRoute
  '/careersync/notifications': typeof CareersyncNotificationsRoute
  '/careersync/verified-recruiters': typeof CareersyncVerifiedRecruitersRoute
  '/careersync-academy/': typeof CareersyncAcademyIndexRoute
  '/api/public/report-error': typeof ApiPublicReportErrorRoute
  '/careersync-academy/courses/$courseId': typeof CareersyncAcademyCoursesCourseIdRouteWithChildren
  '/careersync/blogs/$slug': typeof CareersyncBlogsSlugRoute
  '/careersync-academy/courses/$courseId/$unitId': typeof CareersyncAcademyCoursesCourseIdUnitIdRoute
  '/careersync-academy/courses/$courseId/': typeof CareersyncAcademyCoursesCourseIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ats-score-checker'
    | '/bechnaseekho'
    | '/careersync'
    | '/careersync-academy'
    | '/contact'
    | '/cookies'
    | '/find-jobs'
    | '/login'
    | '/partners'
    | '/post-job'
    | '/pricing'
    | '/privacy'
    | '/resources'
    | '/resume-templates'
    | '/services'
    | '/signup'
    | '/terms'
    | '/api/chat'
    | '/careersync/about'
    | '/careersync/blogs'
    | '/careersync/jobs'
    | '/careersync/journey'
    | '/careersync/notifications'
    | '/careersync/verified-recruiters'
    | '/careersync-academy/'
    | '/api/public/report-error'
    | '/careersync-academy/courses/$courseId'
    | '/careersync/blogs/$slug'
    | '/careersync-academy/courses/$courseId/$unitId'
    | '/careersync-academy/courses/$courseId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ats-score-checker'
    | '/bechnaseekho'
    | '/careersync'
    | '/contact'
    | '/cookies'
    | '/find-jobs'
    | '/login'
    | '/partners'
    | '/post-job'
    | '/pricing'
    | '/privacy'
    | '/resources'
    | '/resume-templates'
    | '/services'
    | '/signup'
    | '/terms'
    | '/api/chat'
    | '/careersync/about'
    | '/careersync/blogs'
    | '/careersync/jobs'
    | '/careersync/journey'
    | '/careersync/notifications'
    | '/careersync/verified-recruiters'
    | '/careersync-academy'
    | '/api/public/report-error'
    | '/careersync/blogs/$slug'
    | '/careersync-academy/courses/$courseId/$unitId'
    | '/careersync-academy/courses/$courseId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ats-score-checker'
    | '/bechnaseekho'
    | '/careersync'
    | '/careersync-academy'
    | '/contact'
    | '/cookies'
    | '/find-jobs'
    | '/login'
    | '/partners'
    | '/post-job'
    | '/pricing'
    | '/privacy'
    | '/resources'
    | '/resume-templates'
    | '/services'
    | '/signup'
    | '/terms'
    | '/api/chat'
    | '/careersync/about'
    | '/careersync/blogs'
    | '/careersync/jobs'
    | '/careersync/journey'
    | '/careersync/notifications'
    | '/careersync/verified-recruiters'
    | '/careersync-academy/'
    | '/api/public/report-error'
    | '/careersync-academy/courses/$courseId'
    | '/careersync/blogs/$slug'
    | '/careersync-academy/courses/$courseId/$unitId'
    | '/careersync-academy/courses/$courseId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AtsScoreCheckerRoute: typeof AtsScoreCheckerRoute
  BechnaseekhoRoute: typeof BechnaseekhoRoute
  CareersyncRoute: typeof CareersyncRouteWithChildren
  CareersyncAcademyRoute: typeof CareersyncAcademyRouteWithChildren
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  FindJobsRoute: typeof FindJobsRoute
  LoginRoute: typeof LoginRoute
  PartnersRoute: typeof PartnersRoute
  PostJobRoute: typeof PostJobRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRoute
  ResumeTemplatesRoute: typeof ResumeTemplatesRoute
  ServicesRoute: typeof ServicesRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicReportErrorRoute: typeof ApiPublicReportErrorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ats-score-checker': {
      id: '/ats-score-checker'
      path: '/ats-score-checker'
      fullPath: '/ats-score-checker'
      preLoaderRoute: typeof AtsScoreCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bechnaseekho': {
      id: '/bechnaseekho'
      path: '/bechnaseekho'
      fullPath: '/bechnaseekho'
      preLoaderRoute: typeof BechnaseekhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careersync': {
      id: '/careersync'
      path: '/careersync'
      fullPath: '/careersync'
      preLoaderRoute: typeof CareersyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careersync-academy': {
      id: '/careersync-academy'
      path: '/careersync-academy'
      fullPath: '/careersync-academy'
      preLoaderRoute: typeof CareersyncAcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-jobs': {
      id: '/find-jobs'
      path: '/find-jobs'
      fullPath: '/find-jobs'
      preLoaderRoute: typeof FindJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-job': {
      id: '/post-job'
      path: '/post-job'
      fullPath: '/post-job'
      preLoaderRoute: typeof PostJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-templates': {
      id: '/resume-templates'
      path: '/resume-templates'
      fullPath: '/resume-templates'
      preLoaderRoute: typeof ResumeTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careersync-academy/': {
      id: '/careersync-academy/'
      path: '/'
      fullPath: '/careersync-academy/'
      preLoaderRoute: typeof CareersyncAcademyIndexRouteImport
      parentRoute: typeof CareersyncAcademyRoute
    }
    '/careersync/about': {
      id: '/careersync/about'
      path: '/about'
      fullPath: '/careersync/about'
      preLoaderRoute: typeof CareersyncAboutRouteImport
      parentRoute: typeof CareersyncRoute
    }
    '/careersync/blogs': {
      id: '/careersync/blogs'
      path: '/blogs'
      fullPath: '/careersync/blogs'
      preLoaderRoute: typeof CareersyncBlogsRouteImport
      parentRoute: typeof CareersyncRoute
    }
    '/careersync/jobs': {
      id: '/careersync/jobs'
      path: '/jobs'
      fullPath: '/careersync/jobs'
      preLoaderRoute: typeof CareersyncJobsRouteImport
      parentRoute: typeof CareersyncRoute
    }
    '/careersync/journey': {
      id: '/careersync/journey'
      path: '/journey'
      fullPath: '/careersync/journey'
      preLoaderRoute: typeof CareersyncJourneyRouteImport
      parentRoute: typeof CareersyncRoute
    }
    '/careersync/notifications': {
      id: '/careersync/notifications'
      path: '/notifications'
      fullPath: '/careersync/notifications'
      preLoaderRoute: typeof CareersyncNotificationsRouteImport
      parentRoute: typeof CareersyncRoute
    }
    '/careersync/verified-recruiters': {
      id: '/careersync/verified-recruiters'
      path: '/verified-recruiters'
      fullPath: '/careersync/verified-recruiters'
      preLoaderRoute: typeof CareersyncVerifiedRecruitersRouteImport
      parentRoute: typeof CareersyncRoute
    }
    '/api/public/report-error': {
      id: '/api/public/report-error'
      path: '/api/public/report-error'
      fullPath: '/api/public/report-error'
      preLoaderRoute: typeof ApiPublicReportErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careersync-academy/courses/$courseId': {
      id: '/careersync-academy/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/careersync-academy/courses/$courseId'
      preLoaderRoute: typeof CareersyncAcademyCoursesCourseIdRouteImport
      parentRoute: typeof CareersyncAcademyRoute
    }
    '/careersync/blogs/$slug': {
      id: '/careersync/blogs/$slug'
      path: '/$slug'
      fullPath: '/careersync/blogs/$slug'
      preLoaderRoute: typeof CareersyncBlogsSlugRouteImport
      parentRoute: typeof CareersyncBlogsRoute
    }
    '/careersync-academy/courses/$courseId/': {
      id: '/careersync-academy/courses/$courseId/'
      path: '/'
      fullPath: '/careersync-academy/courses/$courseId/'
      preLoaderRoute: typeof CareersyncAcademyCoursesCourseIdIndexRouteImport
      parentRoute: typeof CareersyncAcademyCoursesCourseIdRoute
    }
    '/careersync-academy/courses/$courseId/$unitId': {
      id: '/careersync-academy/courses/$courseId/$unitId'
      path: '/$unitId'
      fullPath: '/careersync-academy/courses/$courseId/$unitId'
      preLoaderRoute: typeof CareersyncAcademyCoursesCourseIdUnitIdRouteImport
      parentRoute: typeof CareersyncAcademyCoursesCourseIdRoute
    }
  }
}

interface CareersyncBlogsRouteChildren {
  CareersyncBlogsSlugRoute: typeof CareersyncBlogsSlugRoute
}

const CareersyncBlogsRouteChildren: CareersyncBlogsRouteChildren = {
  CareersyncBlogsSlugRoute: CareersyncBlogsSlugRoute,
}

const CareersyncBlogsRouteWithChildren = CareersyncBlogsRoute._addFileChildren(
  CareersyncBlogsRouteChildren,
)

interface CareersyncRouteChildren {
  CareersyncAboutRoute: typeof CareersyncAboutRoute
  CareersyncBlogsRoute: typeof CareersyncBlogsRouteWithChildren
  CareersyncJobsRoute: typeof CareersyncJobsRoute
  CareersyncJourneyRoute: typeof CareersyncJourneyRoute
  CareersyncNotificationsRoute: typeof CareersyncNotificationsRoute
  CareersyncVerifiedRecruitersRoute: typeof CareersyncVerifiedRecruitersRoute
}

const CareersyncRouteChildren: CareersyncRouteChildren = {
  CareersyncAboutRoute: CareersyncAboutRoute,
  CareersyncBlogsRoute: CareersyncBlogsRouteWithChildren,
  CareersyncJobsRoute: CareersyncJobsRoute,
  CareersyncJourneyRoute: CareersyncJourneyRoute,
  CareersyncNotificationsRoute: CareersyncNotificationsRoute,
  CareersyncVerifiedRecruitersRoute: CareersyncVerifiedRecruitersRoute,
}

const CareersyncRouteWithChildren = CareersyncRoute._addFileChildren(
  CareersyncRouteChildren,
)

interface CareersyncAcademyCoursesCourseIdRouteChildren {
  CareersyncAcademyCoursesCourseIdUnitIdRoute: typeof CareersyncAcademyCoursesCourseIdUnitIdRoute
  CareersyncAcademyCoursesCourseIdIndexRoute: typeof CareersyncAcademyCoursesCourseIdIndexRoute
}

const CareersyncAcademyCoursesCourseIdRouteChildren: CareersyncAcademyCoursesCourseIdRouteChildren =
  {
    CareersyncAcademyCoursesCourseIdUnitIdRoute:
      CareersyncAcademyCoursesCourseIdUnitIdRoute,
    CareersyncAcademyCoursesCourseIdIndexRoute:
      CareersyncAcademyCoursesCourseIdIndexRoute,
  }

const CareersyncAcademyCoursesCourseIdRouteWithChildren =
  CareersyncAcademyCoursesCourseIdRoute._addFileChildren(
    CareersyncAcademyCoursesCourseIdRouteChildren,
  )

interface CareersyncAcademyRouteChildren {
  CareersyncAcademyIndexRoute: typeof CareersyncAcademyIndexRoute
  CareersyncAcademyCoursesCourseIdRoute: typeof CareersyncAcademyCoursesCourseIdRouteWithChildren
}

const CareersyncAcademyRouteChildren: CareersyncAcademyRouteChildren = {
  CareersyncAcademyIndexRoute: CareersyncAcademyIndexRoute,
  CareersyncAcademyCoursesCourseIdRoute:
    CareersyncAcademyCoursesCourseIdRouteWithChildren,
}

const CareersyncAcademyRouteWithChildren =
  CareersyncAcademyRoute._addFileChildren(CareersyncAcademyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AtsScoreCheckerRoute: AtsScoreCheckerRoute,
  BechnaseekhoRoute: BechnaseekhoRoute,
  CareersyncRoute: CareersyncRouteWithChildren,
  CareersyncAcademyRoute: CareersyncAcademyRouteWithChildren,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  FindJobsRoute: FindJobsRoute,
  LoginRoute: LoginRoute,
  PartnersRoute: PartnersRoute,
  PostJobRoute: PostJobRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRoute,
  ResumeTemplatesRoute: ResumeTemplatesRoute,
  ServicesRoute: ServicesRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublicReportErrorRoute: ApiPublicReportErrorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
