
-- 1) Extend jobs table with detailed fields
ALTER TABLE public.jobs
  ADD COLUMN IF NOT EXISTS external_id TEXT UNIQUE,
  ADD COLUMN IF NOT EXISTS industry TEXT,
  ADD COLUMN IF NOT EXISTS shift TEXT,
  ADD COLUMN IF NOT EXISTS open_positions INTEGER,
  ADD COLUMN IF NOT EXISTS responsibilities TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS required_skills TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS preferred_skills TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS benefits TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS office_address TEXT,
  ADD COLUMN IF NOT EXISTS company_overview TEXT,
  ADD COLUMN IF NOT EXISTS company_website TEXT,
  ADD COLUMN IF NOT EXISTS recruiter_whatsapp TEXT,
  ADD COLUMN IF NOT EXISTS recruiter_notes TEXT,
  ADD COLUMN IF NOT EXISTS application_deadline DATE,
  ADD COLUMN IF NOT EXISTS is_verified BOOLEAN NOT NULL DEFAULT false;

-- 2) Seed 6 verified live openings
INSERT INTO public.jobs (
  external_id, role, company, location, experience, salary, employment_type,
  description, tags, is_active, status, is_verified,
  industry, shift, open_positions,
  responsibilities, required_skills, preferred_skills, benefits,
  office_address, company_overview, company_website,
  recruiter_whatsapp, recruiter_notes, application_deadline
) VALUES
(
  'assure-capital-insurance-advisor',
  'Insurance Advisor', 'Assure Capital', 'Delhi, India',
  '0-6 Years', '₹15K - ₹30K / month', 'Full-time',
  'Join Assure Capital to help customers choose suitable life, motor, and health insurance plans while maintaining service quality.',
  ARRAY['Insurance','Sales','Customer Service'], true, 'approved', true,
  'Insurance', '10 AM - 6 PM', 59,
  ARRAY['Understand customer requirements and suggest policy options','Handle end-to-end insurance application workflow','Coordinate with internal underwriting and operations'],
  ARRAY['Good Communication Skills','Positive Attitude','Basic Calling and Follow-Up Skills'],
  ARRAY['Communication Skills','Hindi + English','MS Excel'],
  ARRAY['Health Insurance','WFH Option','Annual Bonus'],
  'Delhi, India',
  'Assure Capital is a Delhi-based insurance company focused on dependable financial protection products.',
  NULL, '919810001111',
  'Freshers are welcome. Training is provided in office.',
  '2026-09-15'
),
(
  'apna-screening-network-sales-manager',
  'Sales Manager', 'Apna Screening Network', 'Delhi NCR',
  '3-8 Years', '₹40,000 - ₹50,000 / month + ₹5,000 travel allowance', 'Full-time',
  'Lead field sales operations, merchant acquisition, team performance, and business growth.',
  ARRAY['Advertising','Sales','Team Management'], true, 'approved', true,
  'Advertising', 'Day Shift', 1,
  ARRAY['Manage Team Leaders and Field Sales Executives','Monitor sales activities and merchant onboarding','Conduct reviews and performance tracking','Submit MIS and performance reports'],
  ARRAY['Field Sales Operations','Team Handling','CRM','MIS Reporting'],
  ARRAY['Merchant Acquisition','Performance Tracking'],
  ARRAY['Health Insurance','Travel Allowance','Performance Incentives'],
  'Sector 18, Noida, Uttar Pradesh 201301',
  'Apna Screening Network supports brands with scalable advertising operations and lead programs.',
  'https://www.apna.co', '919810002222',
  'Team handling experience is mandatory. Includes a 7-day offline training and evaluation program, unpaid training, and mandatory registered and administrative office attendance.',
  '2026-08-30'
),
(
  'apna-screening-network-team-leader',
  'Team Leader (Field Sales)', 'Apna Screening Network', 'Delhi NCR',
  '3-8 Years', '₹30,000 - ₹40,000 / month + ₹5,000 travel allowance', 'Full-time',
  'Manage Team Leaders and Field Sales Executives while driving performance and reporting discipline.',
  ARRAY['Advertising','Field Sales','Leadership'], true, 'approved', true,
  'Advertising', '10 AM - 6 PM', 42,
  ARRAY['Manage Team Leaders','Field Sales Executives','Conduct Reviews','Performance Tracking','Submit MIS','Performance Reports'],
  ARRAY['Team Management','Merchant Onboarding','CRM Reporting'],
  ARRAY['Sales Closures','Target Achievement'],
  ARRAY['Travel Allowance','Team Performance Incentives'],
  'Delhi NCR',
  'Apna Screening Network delivers customer engagement operations with measurable outcomes.',
  NULL, '919810002222',
  'Includes a 7-day offline training and evaluation program, unpaid training, and mandatory registered and administrative office attendance.',
  '2026-09-10'
),
(
  'policy-meta-insurance-consultant',
  'Insurance Consultant', 'Policy Meta', 'Noida, Uttar Pradesh',
  '0-6 Years', '₹15K - ₹30K / month', 'Full-time',
  'Help customers choose policy options and assist with complete onboarding documentation.',
  ARRAY['Insurance','Advisory','Sales'], true, 'approved', true,
  'Insurance', '10 AM - 6 PM', 99,
  ARRAY['Good communication skills','Positive attitude','Basic calling and follow-up skills'],
  ARRAY['Insurance Advisory','Client Follow-up'],
  ARRAY['Cross-selling','Channel Sales','Communication Skills','Target Achievement','Hindi + English'],
  ARRAY['Medical Insurance','Performance Bonus'],
  'Noida Sector 3 G34 First Floor, Office No. F2, Near Sector 16 Metro Station',
  'Policy Meta connects customers with reliable insurance offerings and dedicated advisory support.',
  NULL, '919810003333',
  'Candidate should be comfortable with phone and WhatsApp communication.',
  '2026-08-25'
),
(
  'smile-india-trust-program-coordinator',
  'Program Coordinator', 'Smile India Trust', 'Noida, Uttar Pradesh',
  '0-6 Years', '₹15,100 / month', 'Full-time',
  'Coordinate grassroots social programs and manage reporting across NGO initiatives.',
  ARRAY['NGO','Coordination','Impact'], true, 'approved', true,
  'NGO', '10 AM - 6 PM', 49,
  ARRAY['Coordinate project timelines and volunteers','Compile monthly impact reports','Work with partner organizations'],
  ARRAY['Program Coordination','Documentation','Stakeholder Communication'],
  ARRAY['NGO Experience','Event Planning'],
  ARRAY['Health Insurance','Learning Budget','Impact Programs'],
  'Noida Sector 4, Near By Sector 16 Metro Station',
  'Smile India Trust drives social impact through education and community outreach programs.',
  NULL, '919810004444',
  'Passion for social impact is important.',
  '2026-09-05'
),
(
  'scaler-academy-counsellor',
  'Business Development Associate (BDA)', 'Scaler Academy', 'Gurugram, Haryana',
  '0-6 Years', 'Up to ₹5.5 LPA', 'Full-time',
  'Guide learners through suitable upskilling pathways and support admissions conversion.',
  ARRAY['EdTech','Sales','Counselling'], true, 'approved', true,
  'EdTech', '12 PM - 9 PM', 70,
  ARRAY['Good communication skills','Positive attitude'],
  ARRAY['Counselling','Lead Nurturing'],
  ARRAY['Communication Skills','EdTech Experience','CRM'],
  ARRAY['Health Insurance','ESOPs','Learning Budget','Virtual Interview','Week Off - Sunday and Monday'],
  'Think Plan Workplace 18-B, Institutional Area, Sector 32, Gurugram, Haryana',
  'Scaler Academy helps professionals level up software careers with intensive technology programs.',
  NULL, '919810005555',
  'Excellent communication and a positive attitude are required. Complete in-office training and process support are provided. Virtual interview is available. Week off: Sunday and Monday.',
  '2026-09-20'
)
ON CONFLICT (external_id) DO UPDATE SET
  role = EXCLUDED.role,
  company = EXCLUDED.company,
  location = EXCLUDED.location,
  experience = EXCLUDED.experience,
  salary = EXCLUDED.salary,
  employment_type = EXCLUDED.employment_type,
  description = EXCLUDED.description,
  tags = EXCLUDED.tags,
  is_active = EXCLUDED.is_active,
  status = EXCLUDED.status,
  is_verified = EXCLUDED.is_verified,
  industry = EXCLUDED.industry,
  shift = EXCLUDED.shift,
  open_positions = EXCLUDED.open_positions,
  responsibilities = EXCLUDED.responsibilities,
  required_skills = EXCLUDED.required_skills,
  preferred_skills = EXCLUDED.preferred_skills,
  benefits = EXCLUDED.benefits,
  office_address = EXCLUDED.office_address,
  company_overview = EXCLUDED.company_overview,
  company_website = EXCLUDED.company_website,
  recruiter_whatsapp = EXCLUDED.recruiter_whatsapp,
  recruiter_notes = EXCLUDED.recruiter_notes,
  application_deadline = EXCLUDED.application_deadline,
  updated_at = now();
